### ISSUE TITLE
Update the main layout

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Quake-Report#1]
Currently, the earthquake list is displayed as a list. Try to change the layout by introducing a [card layout](https://developer.android.com/guide/topics/ui/layout/cardview). Make it more [Material](https://material.io/).

**Comment by se7kn8** [comment]
I can work on this

**Comment by Kvaibhav01** [comment]
Great! Go ahead @SE7-KN8

**Comment by bradcypert** [comment]
Is this closed then?

**Comment by Kvaibhav01** [comment]
@bradcypert sorry, it's closed. You can look for another issue. 😀
