### ISSUE TITLE
Shift all the three dots menu to navigation drawer

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Quake-Report#11]
Move all the options (three dots menu) to a left nav drawer. You can use MikePenz's [Material Drawer library](https://github.com/mikepenz/MaterialDrawer) for this.

**Comment by akhil-gautam** [comment]
Can I help on this?

**Comment by muhrahmatullah** [comment]
hey, did anybody already working on this?

**Comment by alistairholmes** [comment]
I've been trying to work on this issue, but having problems with aapt2.

**Comment by Kvaibhav01** [comment]
@akhil-gautam, go ahead. If you can't then @muhrahmatullah will take over.

**Comment by Kvaibhav01** [comment]
@alistairholmes, in the gradle.properties file, use this:

**Comment by Kvaibhav01** [comment]
@alistairholmes, in the gradle.properties file, use this:

`android.enableAapt2=false`

Reference:
https://stackoverflow.com/a/46988209

**Comment by alistairholmes** [comment]
thanks @Kvaibhav01 I tried that but it didn't work which was very weird.

**Comment by Kvaibhav01** [comment]
@alistairholmes, can you show us the screenshot of the error or the logcat? Maybe others can help. @akhil-gautam @muhrahmatullah

**Comment by alistairholmes** [comment]
@Kvaibhav01 thanks it seems to have fixed itself now.

**Comment by wseemann** [comment]
I just submitted a PR for this: https://github.com/Kvaibhav01/Quake-Info/pull/18

**Comment by ranaharshit999** [comment]
i want to work on this issue

**Comment by Kvaibhav01** [comment]
@ranaharshit999 go ahead!

**Comment by je856vj** [comment]
Greetings, i would like to contribute to the project by working on this issue, could i join as well ?

**Comment by ranaharshit999** [comment]
Check out my PR #20

**Comment by Kvaibhav01** [comment]
Completed by @wseemann #19. Thank you all for your efforts. Others can try solving the [remaining issues](https://github.com/Kvaibhav01/Quake-Info/issues).
