### ISSUE TITLE
Add a dark theme

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Quake-Report#12]
This option will be listed on the _Settings_ option in the nav drawer.

**Comment by ranaharshit999** [comment]
i want to work on this issue but tell me exactly where do u want the dark theme

**Comment by Kvaibhav01** [comment]
@ranaharshit999 it's already mentioned in the issue description.

**Comment by je856vj** [comment]
Hey there, can i join in on this issue too ? I can do it even today.

**Comment by Kvaibhav01** [comment]
Hi @je856vj, sure. I'll assign you this.

**Comment by je856vj** [comment]
Hello there, additionaly, i want to ask, if you want the Settings option in the drawer open the Settings activity, with added Dark theme option at the bottom ? Also, as i'm almost done, can you specify the colors, or should i go for some default dark theme colors ?

**Comment by Kvaibhav01** [comment]
Hi @je856vj, yes add the dark theme option inside the Settings activity at the bottom and you can go for the default dark theme colors.

**Comment by je856vj** [comment]
Hey again, check out the #21 . In addition i made a minor fix for the drawer closing (onBackPressed).
