### ISSUE TITLE
Add pull-to-refresh list

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Quake-Report#13]
When the homepage of the app is pulled, it should refresh the list of earthquakes. After the list is updated, a [`Toast`](https://developer.android.com/guide/topics/ui/notifiers/toasts) message should occur.  

References:
- https://guides.codepath.com/android/implementing-pull-to-refresh-guide
- https://developer.android.com/training/swipe/add-swipe-interface

**Comment by alistairholmes** [comment]
Is anyone working on this issue?

**Comment by NayakNavin** [comment]
I've added swipe refresh (pull to refresh)

**Comment by alistairholmes** [comment]
@NayakNavin sorry PR was already sent for this issue :/

**Comment by Kvaibhav01** [comment]
@alistairholmes, there are some issues [here](https://github.com/Kvaibhav01/Quake-Info/pull/15#pullrequestreview-163364619).

**Comment by rahmatsyam** [comment]
Hi, I will try fix it

**Comment by Kvaibhav01** [comment]
@rahmatsyam okay!

**Comment by ranaharshit999** [comment]
i want to work on this issue

**Comment by Kvaibhav01** [comment]
@ranaharshit999 thanks for your interest. I'll wait for @rahmatsyam.

**Comment by Kvaibhav01** [comment]
Closing as it's implemented.
